tclmode

# Generated by Genus(TM) Synthesis Solution 19.10-p002_1, revision 1.334b
# Generated on: Tue May 13 14:56:56 MSK 2025 (Tue May 13 11:56:56 GMT 2025)

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file fv/kogge_stone/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/kogge_stone -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 4 -norelease_license
set_compare_options -threads 4

set env(RC_VERSION)     "19.10-p002_1"
set env(CDN_SYNTH_ROOT) "/local/tools/cadence/GENIUS/191/tools"
set CDN_SYNTH_ROOT      "/local/tools/cadence/GENIUS/191/tools"
set env(CW_DIR) "/local/tools/cadence/GENIUS/191/tools/lib/chipware"
set CW_DIR      "/local/tools/cadence/GENIUS/191/tools/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . /local/tools/cadence/GENIUS/191/tools/lib/tech -library -both
read_library -liberty -both /tools/PDK_DDK/CORELIB8DHS_3.1.a/liberty/wc_1.20V_105C/CORELIB8DHS.lib

set_undriven_signal 0 -golden
set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue. This option is
# only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

add_search_path . -design -golden
read_design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -sv09 ../rtl/fulladder.sv
add_search_path . -design -golden
read_design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -sv09 ../rtl/kogge_stone.sv
add_search_path . -design -golden
read_design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -sv09 ../rtl/pg_node.sv
elaborate_design -golden -root {kogge_stone} -rootonly -rootonly  

read_design -verilog95   -revised -lastmod -noelab fv/kogge_stone/fv_map.v.gz
elaborate_design -revised -root {kogge_stone}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/kogge_stone/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

set_analyze_option -auto

set_system_mode lec
analyze_datapath -module -verbose 
analyze_datapath   -verbose
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

exit

