
// Generated by Cadence Genus(TM) Synthesis Solution 19.10-p002_1
// Generated on: May 13 2025 14:56:56 MSK (May 13 2025 11:56:56 UTC)

// Verification Directory fv/kogge_stone 

module pg_node(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__8780(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__4296(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_1(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__3772(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__1474(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_2(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__4547(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__9682(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_3(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__2683(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__1309(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_4(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__6877(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__2900(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_5(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__2391(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__7675(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_6(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__7118(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__8757(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_7(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__1786(.A (g_left_old_i), .B (p_right_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__5953(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_8(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHSP g32__5703(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__7114(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_9(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__5266(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__2250(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_10(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__6083(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__2703(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_11(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__5795(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__7344(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_12(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__1840(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__5019(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_13(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__1857(.A (g_left_old_i), .B (p_right_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__9906(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_14(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__8780(.A (g_left_old_i), .B (p_right_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__4296(.A (p_right_old_i), .B (p_left_old_i), .Z
       (p_new_o));
endmodule

module pg_node_15(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__3772(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__1474(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module pg_node_16(p_left_old_i, g_left_old_i, p_right_old_i,
     g_right_old_i, p_new_o, g_new_o);
  input p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  output p_new_o, g_new_o;
  wire p_left_old_i, g_left_old_i, p_right_old_i, g_right_old_i;
  wire p_new_o, g_new_o;
  AO6NHS g32__4547(.A (p_right_old_i), .B (g_left_old_i), .C
       (g_right_old_i), .Z (g_new_o));
  F_AN2HSP g33__9682(.A (p_left_old_i), .B (p_right_old_i), .Z
       (p_new_o));
endmodule

module fulladder(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__2683(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_1(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__1309(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_2(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__6877(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_3(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__2900(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_4(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__2391(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_5(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__7675(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_6(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__7118(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module fulladder_7(a_i, b_i, carry_i, sum_o, carry_o);
  input a_i, b_i, carry_i;
  output sum_o, carry_o;
  wire a_i, b_i, carry_i;
  wire sum_o, carry_o;
  EO3HS g36__8757(.A (carry_i), .B (a_i), .C (b_i), .Z (sum_o));
endmodule

module kogge_stone(clk_i, aresetn_i, a_i, b_i, c_i, c_o, sum_o);
  input clk_i, aresetn_i, c_i;
  input [7:0] a_i, b_i;
  output c_o;
  output [7:0] sum_o;
  wire clk_i, aresetn_i, c_i;
  wire [7:0] a_i, b_i;
  wire c_o;
  wire [7:0] sum_o;
  wire [7:0] \p_value[0] ;
  wire [7:0] \g_value[0] ;
  wire [7:0] sum_ff;
  wire [8:0] carry;
  wire [7:0] b_ff;
  wire [7:0] a_ff;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire carry_in_ff, \g_value[1][0] , \g_value[1][2] , \g_value[1][3] ,
       \g_value[1][4] , \g_value[1][5] , \g_value[1][6] ,
       \g_value[1][7] ;
  wire \g_value[2][1] , \g_value[2][4] , \g_value[2][5] ,
       \g_value[2][6] , \g_value[2][7] , \g_value[3][2] ,
       \g_value[3][3] , \g_value[3][4] ;
  wire \g_value[3][5] , \g_value[3][6] , \g_value[3][7] , n_0,
       \p_value[1][0] , \p_value[1][2] , \p_value[1][3] ,
       \p_value[1][4] ;
  wire \p_value[1][5] , \p_value[1][6] , \p_value[1][7] ,
       \p_value[2][1] , \p_value[2][4] , \p_value[2][5] ,
       \p_value[2][6] , \p_value[2][7] ;
  wire \p_value[3][2] , \p_value[3][3] , \p_value[3][4] ,
       \p_value[3][5] , \p_value[3][6] , \p_value[3][7] ;
  pg_node \genblk1[1].genblk1[1].genblk1.node_inst (.p_left_old_i
       (\p_value[1][0] ), .g_left_old_i (\g_value[1][0] ),
       .p_right_old_i (\p_value[0] [1]), .g_right_old_i (\g_value[0]
       [1]), .p_new_o (\p_value[2][1] ), .g_new_o (\g_value[2][1] ));
  pg_node_1 \genblk1[1].genblk1[2].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [1]), .g_left_old_i (\g_value[0] [1]),
       .p_right_old_i (\p_value[0] [2]), .g_right_old_i (\g_value[0]
       [2]), .p_new_o (\p_value[1][2] ), .g_new_o (\g_value[1][2] ));
  pg_node_2 \genblk1[1].genblk1[3].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [2]), .g_left_old_i (\g_value[0] [2]),
       .p_right_old_i (\p_value[0] [3]), .g_right_old_i (\g_value[0]
       [3]), .p_new_o (\p_value[1][3] ), .g_new_o (\g_value[1][3] ));
  pg_node_3 \genblk1[1].genblk1[4].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [3]), .g_left_old_i (\g_value[0] [3]),
       .p_right_old_i (\p_value[0] [4]), .g_right_old_i (\g_value[0]
       [4]), .p_new_o (\p_value[1][4] ), .g_new_o (\g_value[1][4] ));
  pg_node_4 \genblk1[1].genblk1[5].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [4]), .g_left_old_i (\g_value[0] [4]),
       .p_right_old_i (\p_value[0] [5]), .g_right_old_i (\g_value[0]
       [5]), .p_new_o (\p_value[1][5] ), .g_new_o (\g_value[1][5] ));
  pg_node_5 \genblk1[1].genblk1[6].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [5]), .g_left_old_i (\g_value[0] [5]),
       .p_right_old_i (\p_value[0] [6]), .g_right_old_i (\g_value[0]
       [6]), .p_new_o (\p_value[1][6] ), .g_new_o (\g_value[1][6] ));
  pg_node_6 \genblk1[1].genblk1[7].genblk1.node_inst (.p_left_old_i
       (\p_value[0] [6]), .g_left_old_i (\g_value[0] [6]),
       .p_right_old_i (\p_value[0] [7]), .g_right_old_i (\g_value[0]
       [7]), .p_new_o (\p_value[1][7] ), .g_new_o (\g_value[1][7] ));
  pg_node_7 \genblk1[2].genblk1[2].genblk1.node_inst (.p_left_old_i
       (\p_value[1][0] ), .g_left_old_i (\g_value[1][0] ),
       .p_right_old_i (\p_value[1][2] ), .g_right_old_i (\g_value[1][2]
       ), .p_new_o (\p_value[3][2] ), .g_new_o (\g_value[3][2] ));
  pg_node_8 \genblk1[2].genblk1[3].genblk1.node_inst (.p_left_old_i
       (\p_value[2][1] ), .g_left_old_i (\g_value[2][1] ),
       .p_right_old_i (\p_value[1][3] ), .g_right_old_i (\g_value[1][3]
       ), .p_new_o (\p_value[3][3] ), .g_new_o (\g_value[3][3] ));
  pg_node_9 \genblk1[2].genblk1[4].genblk1.node_inst (.p_left_old_i
       (\p_value[1][2] ), .g_left_old_i (\g_value[1][2] ),
       .p_right_old_i (\p_value[1][4] ), .g_right_old_i (\g_value[1][4]
       ), .p_new_o (\p_value[2][4] ), .g_new_o (\g_value[2][4] ));
  pg_node_10 \genblk1[2].genblk1[5].genblk1.node_inst (.p_left_old_i
       (\p_value[1][3] ), .g_left_old_i (\g_value[1][3] ),
       .p_right_old_i (\p_value[1][5] ), .g_right_old_i (\g_value[1][5]
       ), .p_new_o (\p_value[2][5] ), .g_new_o (\g_value[2][5] ));
  pg_node_11 \genblk1[2].genblk1[6].genblk1.node_inst (.p_left_old_i
       (\p_value[1][4] ), .g_left_old_i (\g_value[1][4] ),
       .p_right_old_i (\p_value[1][6] ), .g_right_old_i (\g_value[1][6]
       ), .p_new_o (\p_value[2][6] ), .g_new_o (\g_value[2][6] ));
  pg_node_12 \genblk1[2].genblk1[7].genblk1.node_inst (.p_left_old_i
       (\p_value[1][5] ), .g_left_old_i (\g_value[1][5] ),
       .p_right_old_i (\p_value[1][7] ), .g_right_old_i (\g_value[1][7]
       ), .p_new_o (\p_value[2][7] ), .g_new_o (\g_value[2][7] ));
  pg_node_13 \genblk1[3].genblk1[4].genblk1.node_inst (.p_left_old_i
       (\p_value[1][0] ), .g_left_old_i (\g_value[1][0] ),
       .p_right_old_i (\p_value[2][4] ), .g_right_old_i (\g_value[2][4]
       ), .p_new_o (\p_value[3][4] ), .g_new_o (\g_value[3][4] ));
  pg_node_14 \genblk1[3].genblk1[5].genblk1.node_inst (.p_left_old_i
       (\p_value[2][1] ), .g_left_old_i (\g_value[2][1] ),
       .p_right_old_i (\p_value[2][5] ), .g_right_old_i (\g_value[2][5]
       ), .p_new_o (\p_value[3][5] ), .g_new_o (\g_value[3][5] ));
  pg_node_15 \genblk1[3].genblk1[6].genblk1.node_inst (.p_left_old_i
       (\p_value[3][2] ), .g_left_old_i (\g_value[3][2] ),
       .p_right_old_i (\p_value[2][6] ), .g_right_old_i (\g_value[2][6]
       ), .p_new_o (\p_value[3][6] ), .g_new_o (\g_value[3][6] ));
  pg_node_16 \genblk1[3].genblk1[7].genblk1.node_inst (.p_left_old_i
       (\p_value[3][3] ), .g_left_old_i (\g_value[3][3] ),
       .p_right_old_i (\p_value[2][7] ), .g_right_old_i (\g_value[2][7]
       ), .p_new_o (\p_value[3][7] ), .g_new_o (\g_value[3][7] ));
  fulladder \genblk3[0].add_inst (.a_i (a_i[0]), .b_i (b_i[0]),
       .carry_i (carry_in_ff), .sum_o (sum_ff[0]), .carry_o
       (UNCONNECTED));
  fulladder_1 \genblk3[1].add_inst (.a_i (a_i[1]), .b_i (b_i[1]),
       .carry_i (carry[1]), .sum_o (sum_ff[1]), .carry_o
       (UNCONNECTED0));
  fulladder_2 \genblk3[2].add_inst (.a_i (a_i[2]), .b_i (b_i[2]),
       .carry_i (carry[2]), .sum_o (sum_ff[2]), .carry_o
       (UNCONNECTED1));
  fulladder_3 \genblk3[3].add_inst (.a_i (a_i[3]), .b_i (b_i[3]),
       .carry_i (carry[3]), .sum_o (sum_ff[3]), .carry_o
       (UNCONNECTED2));
  fulladder_4 \genblk3[4].add_inst (.a_i (a_i[4]), .b_i (b_i[4]),
       .carry_i (carry[4]), .sum_o (sum_ff[4]), .carry_o
       (UNCONNECTED3));
  fulladder_5 \genblk3[5].add_inst (.a_i (a_i[5]), .b_i (b_i[5]),
       .carry_i (carry[5]), .sum_o (sum_ff[5]), .carry_o
       (UNCONNECTED4));
  fulladder_6 \genblk3[6].add_inst (.a_i (a_i[6]), .b_i (b_i[6]),
       .carry_i (carry[6]), .sum_o (sum_ff[6]), .carry_o
       (UNCONNECTED5));
  fulladder_7 \genblk3[7].add_inst (.a_i (a_i[7]), .b_i (b_i[7]),
       .carry_i (carry[7]), .sum_o (sum_ff[7]), .carry_o
       (UNCONNECTED6));
  F_FD2QHS \sum_o_reg[7] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[7]),
       .Q (sum_o[7]));
  F_FD2QHS \sum_o_reg[6] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[6]),
       .Q (sum_o[6]));
  F_FD2QHS \sum_o_reg[5] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[5]),
       .Q (sum_o[5]));
  F_FD2QHS \sum_o_reg[4] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[4]),
       .Q (sum_o[4]));
  F_FD2QHS \sum_o_reg[3] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[3]),
       .Q (sum_o[3]));
  F_FD2QHS \sum_o_reg[2] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[2]),
       .Q (sum_o[2]));
  F_FD2QHS \sum_o_reg[1] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[1]),
       .Q (sum_o[1]));
  OR2HSP g315__1786(.A (b_ff[0]), .B (a_ff[0]), .Z (\p_value[1][0] ));
  OR2HSP g316__5953(.A (b_ff[1]), .B (a_ff[1]), .Z (\p_value[0] [1]));
  F_AN2HSP g317__5703(.A (a_ff[0]), .B (b_ff[0]), .Z (\g_value[1][0] ));
  F_AN2HSP g318__7114(.A (a_ff[1]), .B (b_ff[1]), .Z (\g_value[0] [1]));
  F_FD2QHS \a_ff_reg[0] (.CD (aresetn_i), .CP (clk_i), .D (a_i[0]), .Q
       (a_ff[0]));
  F_FD2QHS \a_ff_reg[1] (.CD (aresetn_i), .CP (clk_i), .D (a_i[1]), .Q
       (a_ff[1]));
  F_FD2QHS \b_ff_reg[1] (.CD (aresetn_i), .CP (clk_i), .D (b_i[1]), .Q
       (b_ff[1]));
  F_FD2QHS \b_ff_reg[0] (.CD (aresetn_i), .CP (clk_i), .D (b_i[0]), .Q
       (b_ff[0]));
  OR2HSP g311__5266(.A (b_ff[2]), .B (a_ff[2]), .Z (\p_value[0] [2]));
  F_AN2HSP g312__2250(.A (a_ff[2]), .B (b_ff[2]), .Z (\g_value[0] [2]));
  F_FD2QHS \a_ff_reg[2] (.CD (aresetn_i), .CP (clk_i), .D (a_i[2]), .Q
       (a_ff[2]));
  F_FD2QHS \b_ff_reg[2] (.CD (aresetn_i), .CP (clk_i), .D (b_i[2]), .Q
       (b_ff[2]));
  OR2HSP g313__6083(.A (b_ff[3]), .B (a_ff[3]), .Z (\p_value[0] [3]));
  F_AN2HSP g314__2703(.A (a_ff[3]), .B (b_ff[3]), .Z (\g_value[0] [3]));
  F_FD2QHS \a_ff_reg[3] (.CD (aresetn_i), .CP (clk_i), .D (a_i[3]), .Q
       (a_ff[3]));
  F_FD2QHS \b_ff_reg[3] (.CD (aresetn_i), .CP (clk_i), .D (b_i[3]), .Q
       (b_ff[3]));
  OR2HSP g323__5795(.A (b_ff[4]), .B (a_ff[4]), .Z (\p_value[0] [4]));
  F_AN2HSP g324__7344(.A (a_ff[4]), .B (b_ff[4]), .Z (\g_value[0] [4]));
  F_FD2QHS \a_ff_reg[4] (.CD (aresetn_i), .CP (clk_i), .D (a_i[4]), .Q
       (a_ff[4]));
  F_FD2QHS \b_ff_reg[4] (.CD (aresetn_i), .CP (clk_i), .D (b_i[4]), .Q
       (b_ff[4]));
  OR2HSP g325__1840(.A (b_ff[5]), .B (a_ff[5]), .Z (\p_value[0] [5]));
  F_AN2HSP g326__5019(.A (a_ff[5]), .B (b_ff[5]), .Z (\g_value[0] [5]));
  F_FD2QHS \a_ff_reg[5] (.CD (aresetn_i), .CP (clk_i), .D (a_i[5]), .Q
       (a_ff[5]));
  F_FD2QHS \b_ff_reg[5] (.CD (aresetn_i), .CP (clk_i), .D (b_i[5]), .Q
       (b_ff[5]));
  OR2HSP g319__1857(.A (b_ff[6]), .B (a_ff[6]), .Z (\p_value[0] [6]));
  F_AN2HSP g320__9906(.A (a_ff[6]), .B (b_ff[6]), .Z (\g_value[0] [6]));
  F_FD2QHS \a_ff_reg[6] (.CD (aresetn_i), .CP (clk_i), .D (a_i[6]), .Q
       (a_ff[6]));
  F_FD2QHS \b_ff_reg[6] (.CD (aresetn_i), .CP (clk_i), .D (b_i[6]), .Q
       (b_ff[6]));
  AO6NHSP g418__8780(.A (\p_value[3][6] ), .B (carry[6]), .C
       (\g_value[3][6] ), .Z (carry[7]));
  AO6NHSP g419__4296(.A (\p_value[3][5] ), .B (carry[5]), .C
       (\g_value[3][5] ), .Z (carry[6]));
  AO6NHSP g420__3772(.A (\p_value[3][4] ), .B (carry[4]), .C
       (\g_value[3][4] ), .Z (carry[5]));
  AO6NHSP g421__1474(.A (\p_value[3][3] ), .B (carry[3]), .C
       (\g_value[3][3] ), .Z (carry[4]));
  AO6NHSP g422__4547(.A (\p_value[3][2] ), .B (carry[2]), .C
       (\g_value[3][2] ), .Z (carry[3]));
  AO6NHSP g423__9682(.A (\p_value[2][1] ), .B (carry[1]), .C
       (\g_value[2][1] ), .Z (carry[2]));
  OR2HSP g424__2683(.A (b_ff[7]), .B (a_ff[7]), .Z (\p_value[0] [7]));
  F_AN2HSP g425__1309(.A (a_ff[7]), .B (b_ff[7]), .Z (\g_value[0] [7]));
  AO6NHSP g426__6877(.A (\p_value[1][0] ), .B (carry_in_ff), .C
       (\g_value[1][0] ), .Z (carry[1]));
  F_FD2QHS \a_ff_reg[7] (.CD (aresetn_i), .CP (clk_i), .D (a_i[7]), .Q
       (a_ff[7]));
  F_FD2QHS \b_ff_reg[7] (.CD (aresetn_i), .CP (clk_i), .D (b_i[7]), .Q
       (b_ff[7]));
  F_FD2QHS c_o_reg(.CD (aresetn_i), .CP (clk_i), .D (n_0), .Q (c_o));
  AO6NHSP g429__2900(.A (\p_value[3][7] ), .B (carry[7]), .C
       (\g_value[3][7] ), .Z (n_0));
  F_FD2QHS \sum_o_reg[0] (.CD (aresetn_i), .CP (clk_i), .D (sum_ff[0]),
       .Q (sum_o[0]));
  F_FD2QHS carry_in_ff_reg(.CD (aresetn_i), .CP (clk_i), .D (c_i), .Q
       (carry_in_ff));
endmodule

